job:
  KIND: TrainingJob
  inputs:
    KIND: ParquetReader
    path: data/inputs.parquet
  targets:
    KIND: ParquetReader
    path: data/targets.parquet
  serializer:
    KIND: JoblibModelSerializer
    path: models/model.joblib
