"""Generate runtime environment exports from uv.lock without changing resolution.

Run with Python 3.13 from any directory. Use --check in CI to reject drift.
Platform markers are retained verbatim in both exports.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys

ROOT: Path = Path(__file__).resolve().parents[1]


def render_exports() -> dict[Path, str]:
    """Resolve no new versions and render the two runtime installation files."""
    command: list[str] = [
        "uv",
        "export",
        "--locked",
        "--no-default-groups",
        "--no-emit-project",
        "--no-editable",
        "--no-hashes",
        "--no-header",
        "--format=requirements-txt",
    ]
    result: subprocess.CompletedProcess[str] = subprocess.run(
        command, cwd=ROOT, check=True, capture_output=True, text=True
    )
    # Keep each requirement intact, especially its conditional platform marker.
    requirements: list[str] = [
        line
        for line in result.stdout.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    environment: dict[str, str | list[str]] = {
        "python": (ROOT / ".python-version").read_text(encoding="utf-8").strip(),
        "dependencies": requirements,
    }
    header: str = "# Generated by scripts/export_environment.py from uv.lock. Do not edit.\n"
    return {
        ROOT / "requirements.txt": header + "\n".join(requirements) + "\n",
        ROOT / "python_env.yaml": json.dumps(environment, indent=4) + "\n",
    }


def main() -> int:
    """Write exports, or report stale files without modifying them."""
    parser: argparse.ArgumentParser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if exports differ.")
    args: argparse.Namespace = parser.parse_args()
    try:
        exports: dict[Path, str] = render_exports()
    except subprocess.CalledProcessError as error:
        print(error.stderr, file=sys.stderr)
        return 1
    stale: list[str] = []
    for path, content in exports.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.name)
        else:
            path.write_text(content, encoding="utf-8")
    if stale:
        print("Stale environment exports: " + ", ".join(stale), file=sys.stderr)
        print("Run python scripts/export_environment.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
